name: Build and test lab-cicd
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    name: Test cicd-lab
    steps:
      - uses: actions/checkout@v3

      - name: install dep
        run: npm ci

      - name: run unit test
        run: npm run test